# Generated by Django 3.2.12 on 2022-02-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='furnitures', verbose_name='furniture_image'),
        ),
    ]
