# Generated by Django 3.2.12 on 2022-03-13 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_furniture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopname',
            name='delivary',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='shopname',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shopname',
            name='hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopname',
            name='service',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='areaname',
            name='area',
            field=models.CharField(choices=[('EAST', 'East'), ('WEST', 'West'), ('NORTH', 'North'), ('SOUTH', 'South'), ('CENTRAL', 'Central')], default='EAST', max_length=50),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.shopname')),
            ],
        ),
    ]
