# Generated by Django 3.2.12 on 2022-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220313_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='offer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='furniture',
            name='reference',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
