# Generated by Django 3.2.12 on 2022-06-08 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220313_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.furniture')),
            ],
        ),
    ]
