# Generated by Django 3.2.12 on 2022-06-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20220608_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='furniture',
        ),
        migrations.CreateModel(
            name='OrderedFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.furniture')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.order')),
            ],
        ),
    ]
