# Generated by Django 3.2.12 on 2024-04-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20220608_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaname',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
